---
# This playbook installs Google-Chrome

- name: Install additional repos 
  dnf: name=fedora-workstation-repositories state=latest

- name: Install Google-Chrome package
  dnf: name=google-chrome-stable enablerepo=google-chrome state=present
