- name: Install main packages
  dnf: name={{ item }} state=latest
  with_items:
    - vim
    - wget
    - git
    - gedit
    - ipython
    - python-virtualenv
    - mc
    - cryptsetup
    - unrar
    - nmap
    - ffmpeg
    - htop
    - gnome-disk-utility
    - gimp
    - fuse-exfat
    - exfat-utils
    - fedora-workstation-repositories
    - tmux
    - openfortivpn
    - NetworkManager-fortisslvpn-gnome
    - cassandra
    - python2-virtualenv
    - python3-virtualenv
    - postgresql-devel
  tags: pkgs
