---
# This playbook installs pycharm

- name: Install additional repos
  dnf: name=fedora-workstation-repositories state=latest

- name: Install pycharm package
  dnf: name=pycharm-community enablerepo=phracek-PyCharm state=present
